"""added username field

Revision ID: 4146b9df8eea
Revises: ef4f25ee32e9
Create Date: 2022-08-27 21:52:52.931810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4146b9df8eea"
down_revision = "ef4f25ee32e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    # ### end Alembic commands ###
