"""New Migration

Revision ID: ef4f25ee32e9
Revises: 020943595354
Create Date: 2022-08-27 21:25:57.803614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef4f25ee32e9"
down_revision = "020943595354"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
