version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    ports:
      - 5432:5432

  server:
    build:
      dockerfile: server.Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
